services:
  app:
    depends_on:
      - api
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_B

  api:
   build:
      context: ./backend
      dockerfile: Dockerfile
   ports:
      - "4000:4000"
   environment:
      - NODE_ENV=production
